version: "3"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "8088:8088"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_PORT: ${MYSQL_PORT}
  #     MYSQL_HOST: mysql
  #   depends_on:
  #     - mysql
  #   command:
  #     - ./wait-for-mysql.sh
    
  mysql:
    build:
      context: .
      dockerfile: MYSQL_Dockerfile
    # container_name: mysql_db
    environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PORT: ${MYSQL_PORT}
    restart: always
    ports:
      - "3306:3306"
    expose:
      - 3306